// qwik/tictactoe/src/app.jsx
import { component$ } from "@builder.io/qwik";

import qwikLogo from "./assets/qwik.svg";
import "./app.css";

import TicTacToe from "./TicTacToe";

export const App = component$(() => {
  return (
    <>
      <div>
        <a href="https://qwik.builder.io" target="_blank">
          <img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
        </a>
        <TicTacToe />
      </div>
    </>
  );
});

// preact/tictactoe/src/app.jsx
import { useState } from "preact/hooks";
import preactLogo from "./assets/preact.svg";
import "./app.css";
import TicTacToe from "./TicTacToe";
export function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <div>
        <a href="https://preactjs.com" target="_blank">
          <img src={preactLogo} class="logo preact" alt="Preact logo" />
        </a>
      </div>
      <TicTacToe />
    </>
  );
}
