// react/react-tictactoe/src/App.jsx
import reactLogo from "./assets/react.svg";
import "./App.css";
import TicTacToe from "./TicTacToe";

function App() {
  return (
    <>
      <div>
        <a href="https://react.dev" target="_blank" rel="noopener noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <TicTacToe />
      </div>
    </>
  );
}

export default App;

// qwik/tictactoe/src/app.jsx
import { component$ } from "@builder.io/qwik";

import qwikLogo from "./assets/qwik.svg";
import "./app.css";

import TicTacToe from "./TicTacToe";

export const App = component$(() => {
  return (
    <>
      <div>
        <a href="https://qwik.builder.io" target="_blank">
          <img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
        </a>
        <TicTacToe />
      </div>
    </>
  );
});
