// qwik/tictactoe/src/TicTacToe.jsx
import { component$, useSignal, $ } from "@builder.io/qwik";
import "./TicTacToe.css";
export default component$(() => {
  const initialBoard = Array(9).fill(null);
  const board = useSignal(initialBoard);
  const player = useSignal("X");
  const winner = useSignal(null);

  const checkWinner = $(() => {
    const winPatterns = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (const pattern of winPatterns) {
      const [a, b, c] = pattern;
      if (
        board.value[a] &&
        board.value[a] === board.value[b] &&
        board.value[a] === board.value[c]
      ) {
        winner.value = board.value[a];
        return true;
      }
    }

    if (!board.value.includes(null)) {
      winner.value = "draw";
    }
  });

  const handleClick = $(async (index) => {
    if (board.value[index] || winner.value) return;
    const newBoard = [...board.value];
    newBoard[index] = player.value;
    board.value = newBoard;
    player.value = player.value === "X" ? "O" : "X";
    await checkWinner();
  });

  const resetGame = $(() => {
    board.value = initialBoard;
    player.value = "X";
    winner.value = null;
  });

  const renderBoard = () => {
    return board.value.map((cell, index) => (
      <div
        key={index}
        className={`cell C${index} ${
          cell === "X" || cell === "O" ? "draw-animation" : ""
        }`}
        onClick$={() => handleClick(index)}
      >
        {cell}
      </div>
    ));
  };

  return (
    <div className="tic-tac-toe">
      <div className="board">{renderBoard()}</div>
      <div className="status">
        {winner.value ? (
          winner.value === "draw" ? (
            <p>It's a Draw!</p>
          ) : (
            <p>Player {winner.value} wins!</p>
          )
        ) : (
          <p>Next Player: {player.value}</p>
        )}
      </div>
      <button onClick$={resetGame}>Restart Game</button>
    </div>
  );
});

// react/tictactoe/src/TicTacToe.jsx
import { useState, useEffect } from "react";
import "./TicTacToe.css";
const TicTacToe = () => {
  const initialBoard = Array(9).fill(null);
  const [board, setBoard] = useState(initialBoard);
  const [player, setPlayer] = useState("X");
  const [winner, setWinner] = useState(null);
  useEffect(() => {
    checkWinner();
  }, [board, player, winner]);
  const checkWinner = () => {
    const winPatterns = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (const pattern of winPatterns) {
      const [a, b, c] = pattern;
      if (board[a] && board[a] === board[b] && board[a] === board[c]) {
        setWinner(board[a]);
        return true;
      }
    }

    if (!board.includes(null)) {
      setWinner("draw");
    }
  };

  const handleClick = (index) => {
    if (board[index] || winner) return;
    const newBoard = [...board];
    newBoard[index] = player;
    setBoard(newBoard);
    setPlayer(player === "X" ? "O" : "X");
  };

  const resetGame = () => {
    setBoard(initialBoard);
    setPlayer("X");
    setWinner(null);
  };

  const renderBoard = () => {
    return board.map((cell, index) => (
      <div
        key={index}
        className={`cell ${
          cell === "X" || cell === "O" ? "draw-animation" : ""
        }`}
        onClick={() => handleClick(index)}
      >
        {cell}
      </div>
    ));
  };

  return (
    <div className="tic-tac-toe">
      <div className="board">{renderBoard()}</div>
      <div className="status">
        {winner ? (
          winner === "draw" ? (
            <p>It's a Draw!</p>
          ) : (
            <p>Player {winner} wins!</p>
          )
        ) : (
          <p>Next Player: {player}</p>
        )}
      </div>
      <button onClick={resetGame}>Restart Game</button>
    </div>
  );
};

export default TicTacToe;
