// lit/tictactoe/src/TicTacToe.js
import { LitElement, html, css } from "lit";

class TicTacToe extends LitElement {
  static styles = css`
    .tic-tac-toe {
      text-align: center;
      margin: 20px;
      color: white;
    }

    .board {
      display: grid;
      grid-template-columns: repeat(3, 100px);
      grid-template-rows: repeat(3, 100px);
      gap: 2px;
      padding: 2px;
    }

    .cell {
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 48px;
      background-color: #222;
      color: #fff;
      cursor: pointer;
      transition: background-color 0.2s ease-in-out;
      box-shadow: 0 0 10px #325cffaa;
    }

    .cell:hover {
      background-color: #333;
      filter: drop-shadow(0 0 2em #325cffaa);
    }

    .status {
      margin-top: 10px;
      font-size: 20px;
      color: #fff;
    }

    button {
      margin-top: 10px;
      font-size: 25px;
      padding: 8px 16px;
      background-color: #333;
      color: #fff;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.2s ease-in-out;
    }

    .C0,
    .C1,
    .C3 {
      box-shadow: 0 0 10px rgb(50, 79, 255);
    }
    .C0:hover,
    .C1:hover,
    .C3:hover {
      filter: drop-shadow(0 0 2em rgb(50, 79, 255));
    }
    .C6,
    .C4,
    .C2 {
      box-shadow: 0 0 10px rgba(0, 255, 255, 1);
    }

    .C6:hover,
    .C4:hover,
    .C2:hover {
      filter: drop-shadow(0 0 2em rgba(0, 255, 255, 1));
    }

    .C5,
    .C7,
    .C8 {
      box-shadow: 0 0 10px rgba(50, 79, 255, 1);
    }

    .C5:hover,
    .C7:hover,
    .C8:hover {
      filter: drop-shadow(0 0 2em rgba(50, 79, 255, 1));
    }
    button:hover {
      background: rgb(40, 49, 152);
      background: linear-gradient(
        90deg,
        rgba(40, 49, 152, 1) 33%,
        rgba(50, 79, 255, 1) 57%,
        rgba(0, 255, 255, 1) 80%
      );
      font-weight: bolder;
    }
  `;

  static properties = {
    board: { type: Array },
    player: { type: String },
    winner: { type: String },
  };

  constructor() {
    super();
    this.board = Array(9).fill(null);
    this.player = "X";
    this.winner = null;
  }

  checkWinner() {
    const winPatterns = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (const pattern of winPatterns) {
      const [a, b, c] = pattern;
      if (
        this.board[a] &&
        this.board[a] === this.board[b] &&
        this.board[a] === this.board[c]
      ) {
        this.winner = this.board[a];
        return;
      }
    }

    if (!this.board.includes(null)) {
      this.winner = "draw";
    }
  }

  handleClick(index) {
    if (this.board[index] || this.winner) return;
    this.board[index] = this.player;
    this.checkWinner();
    this.player = this.player === "X" ? "O" : "X";
    this.requestUpdate();
  }

  resetGame() {
    this.board = Array(9).fill(null);
    this.player = "X";
    this.winner = null;
    this.requestUpdate();
  }

  render() {
    return html`
      <div class="tic-tac-toe">
        <div class="board">
          ${this.board.map(
            (cell, index) => html`
              <div
                class="cell C${index}"
                @click="${() => this.handleClick(index)}"
              >
                ${cell}
              </div>
            `
          )}
        </div>
        <div class="status">
          ${this.winner
            ? this.winner === "draw"
              ? html`<p>It's a Draw!</p>`
              : html`<p>Player ${this.winner} wins!</p>`
            : html`<p>Player Turn: ${this.player}</p>`}
        </div>
        <button @click="${this.resetGame}">Restart Game</button>
      </div>
    `;
  }
}

customElements.define("tic-tac-toe", TicTacToe);

// vue/tictactoe/src/components/TicTacToe.vue
<template>
  <div class="tic-tac-toe">
    <div class="board">
      <div
        v-for="(cell, index) in board"
        :key="index"
        :class="[
          'cell',
          `C${index}`,
          { 'draw-animation': cell === 'X' || cell === 'O' },
        ]"
        @click="handleClick(index)"
      >
        {{ cell }}
      </div>
    </div>
    <div class="status">
      <p v-if="winner">
        {{ winner === "draw" ? "It's a Draw!" : `Player ${winner} wins!` }}
      </p>
      <p v-else>Player Turn: {{ player }}</p>
    </div>
    <button @click="resetGame">Restart Game</button>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        initialBoard: Array(9).fill(null),
        board: [...Array(9).fill(null)],
        player: "X",
        winner: null,
      };
    },
    watch: {
      board: "checkWinner",
      player: "checkWinner",
      winner: "checkWinner",
    },
    methods: {
      checkWinner() {
        const winPatterns = [
          [0, 1, 2],
          [3, 4, 5],
          [6, 7, 8],
          [0, 3, 6],
          [1, 4, 7],
          [2, 5, 8],
          [0, 4, 8],
          [2, 4, 6],
        ];

        for (const pattern of winPatterns) {
          const [a, b, c] = pattern;
          if (
            this.board[a] &&
            this.board[a] === this.board[b] &&
            this.board[a] === this.board[c]
          ) {
            this.winner = this.board[a];
            return true;
          }
        }

        if (!this.board.includes(null)) {
          this.winner = "draw";
        }
      },
      handleClick(index) {
        if (this.board[index] || this.winner) return;
        const newBoard = [...this.board];
        newBoard[index] = this.player;
        this.board = newBoard;
        this.player = this.player === "X" ? "O" : "X";
      },
      resetGame() {
        this.board = [...this.initialBoard];
        this.player = "X";
        this.winner = null;
      },
    },
  };
</script>

<style>
  .tic-tac-toe {
    text-align: center;
    margin: 20px;
    color: white;
  }

  .board {
    display: grid;
    grid-template-columns: repeat(3, 100px);
    grid-template-rows: repeat(3, 100px);
    gap: 2px;
    padding: 2px;
  }

  .cell {
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 48px;
    background-color: #222;
    color: #fff;
    cursor: pointer;
    transition: background-color 0.2s ease-in-out;
  }
  .C0,
  .C1,
  .C3 {
    box-shadow: 0 0 10px rgb(65, 184, 131);
  }

  .C2,
  .C4,
  .C6 {
    box-shadow: 0.1rem 0.1rem 5px rgba(53, 73, 94, 1),
      -0.1rem -0.1rem 5px rgb(65, 184, 131);
  }

  .C7,
  .C8,
  .C5 {
    box-shadow: 0 0 10px rgba(53, 73, 94, 1);
  }
  .C0:hover,
  .C1:hover,
  .C3:hover,
  .C4:hover {
    background-color: #333;
    filter: drop-shadow(0 0 2em rgb(65, 184, 131));
  }
  .C7:hover,
  .C8:hover,
  .C5:hover,
  .C6:hover,
  .C2:hover {
    background-color: #333;
    filter: drop-shadow(0 0 2em rgba(53, 73, 94, 1));
  }

  .status {
    margin-top: 10px;
    font-size: 20px;
    color: #fff;
  }

  button {
    margin-top: 10px;
    font-size: 25px;
    padding: 8px 16px;
    background-color: #333;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.2s ease-in-out;
  }

  button:hover {
    background: rgb(65, 184, 131);
    background: linear-gradient(
      90deg,
      rgba(65, 184, 131, 1) 33%,
      rgba(53, 73, 94, 1) 64%
    );
    color: white;
    font-weight: bolder;
  }
</style>
